#!/bin/bash
#
# Script to create and run docker-nova-controller image.
#
set -x
set -e

# Check for Root user
if [ "$(id -u)" != "0" ]; then
    echo "This script must be run as root or with sudo"
    exit 1
fi

# docker-nova-controller Github Repo Name
export REPO_NAME="${REPO_NAME:-}"

# docker-nova-controller Github Repo branch
export REPO_BRANCH="${REPO_BRANCH:-}"

# The name of the Docker base image.
# This should be a RHEL7 image with systemd.
export BASE_IMAGE="${BASE_IMAGE:-rhel7-systemd}"

# Configure the Docker Nova Controller Image Name
export IMAGE_NAME="${IMAGE_NAME:-nova-controller}"

# Configure the DB Host
export DB_HOST="${DB_HOST:-}"

# Configure the DB Password
export DB_PASSWORD="${DB_PASSWORD:-changeme}"

# Configure the RabbitMQ Host
export RABBIT_HOST="${RABBIT_HOST:-}"

# Configure the RabbitMQ User ID
export RABBIT_USER="${RABBIT_USER:-guest}"

# Configure the RabbitMQ User Password
export RABBIT_PASSWORD="${RABBIT_PASSWORD:-guest}"

# IP Address/Hostname of the Keystone server.
export KEYSTONE_HOST="${KEYSTONE_HOST:-127.0.0.1}"

# Configure the TCP port used to connect to the Keystone Admin API.
export KEYSTONE_ADMIN_HOST_PORT="${KEYSTONE_ADMIN_HOST_PORT:-35357}"

# Configure the TCP port used to connect to the Keystone Public API.
export KEYSTONE_PUBLIC_HOST_PORT="${KEYSTONE_PUBLIC_HOST_PORT:-5000}"

# Configure the Service Tenant
export SERVICE_TENANT="${SERVICE_TENANT:-service}"

# Configure the Service Password
export SERVICE_PASSWORD="${SERVICE_PASSWORD:-changeme}"

# Configure the Admin User Password for the admin-openrc file
export ADMIN_USER_PASSWORD="${ADMIN_USER_PASSWORD:-changeme}"

# Configure the Demo User Password for the demo-openrc file
export DEMO_USER_PASSWORD="${DEMO_USER_PASSWORD:-changeme}"

# IP address/Hostname of the Nova API server.
export NOVA_API_HOST="${NOVA_API_HOST:-127.0.0.1}"

# IP address/Hostname of the Glance API server.
export GLANCE_API_HOST="${GLANCE_API_HOST:-127.0.0.1}"

# IP address/Hostname of the Neutron API server.
export NEUTRON_API_HOST="${NEUTRON_API_HOST:-127.0.0.1}"

# Password for connecting to Neutron server in admin context.
export NEUTRON_ADMIN_PASSWORD="${NEUTRON_ADMIN_PASSWORD:-$SERVICE_PASSWORD}"

# Region name for connecting to Neutron server in admin context.
export REGION="${REGION:-RegionOne}"

# Set flag to indicate Neutron will proxy metadata requests and resolve instance IDs.
export SERVICE_NEUTRON_METADATA_PROXY="${SERVICE_NEUTRON_METADATA_PROXY:-true}"

# Shared secret to validate proxied Neutron metadata requests.
export NEUTRON_METADATA_PROXY_SHARED_SECRET="${NEUTRON_METADATA_PROXY_SHARED_SECRET:-changeme}"

# Install docker-nova-controller project
if ! [ -d $HOME/docker-nova-controller ]; then
  git clone -b $REPO_BRANCH https://github.com/danehans/docker-nova-controller.git $HOME/docker-nova-controller
fi

if ! [ -f $HOME/docker-nova-controller/Dockerfile ]; then
  cat <<EOF > $HOME/docker-nova-controller/Dockerfile
# Nova Controller
# VERSION               0.0.1
# Tested on RHEL7 and OSP5 (i.e. Icehouse)

FROM $BASE_IMAGE
MAINTAINER Daneyon Hansen "daneyonhansen@gmail.com"

# Set environment variables within the Nova Controller image/container.
ENV DB_HOST $DB_HOST
ENV DB_PASSWORD $DB_PASSWORD
ENV RABBIT_HOST $RABBIT_HOST
ENV RABBIT_USER $RABBIT_USER
ENV RABBIT_PASSWORD $RABBIT_PASSWORD
ENV KEYSTONE_HOST $KEYSTONE_HOST 
ENV KEYSTONE_ADMIN_HOST_PORT $KEYSTONE_ADMIN_HOST_PORT
ENV KEYSTONE_PUBLIC_HOST_PORT $KEYSTONE_PUBLIC_HOST_PORT
ENV SERVICE_TENANT $SERVICE_TENANT
ENV SERVICE_PASSWORD $SERVICE_PASSWORD
ENV DEMO_USER_PASSWORD $DEMO_USER_PASSWORD
ENV ADMIN_USER_PASSWORD $ADMIN_USER_PASSWORD
ENV NOVA_API_HOST $NOVA_API_HOST
ENV GLANCE_API_HOST $GLANCE_API_HOST
ENV NEUTRON_API_HOST $NEUTRON_API_HOST
ENV REGION $REGION
ENV NEUTRON_ADMIN_PASSWORD $NEUTRON_ADMIN_PASSWORD
ENV SERVICE_NEUTRON_METADATA_PROXY $SERVICE_NEUTRON_METADATA_PROXY
ENV NEUTRON_METADATA_PROXY_SHARED_SECRET $NEUTRON_METADATA_PROXY_SHARED_SECRET

# Set working directory for RUN and CMD instructions.
WORKDIR /root

# Required Utilities. Note: Nova API would error and not start without iptables and cinder client
RUN yum -y install openssl ntp wget rubygems iptables python-cinderclient
RUN systemctl enable ntpd

# Tiller Installation. For more info: https://github.com/markround/tiller
RUN gem install tiller
ADD data/tiller/common.yaml /etc/tiller/common.yaml
ADD data/tiller/environments/production.yaml /etc/tiller/environments/production.yaml
ADD data/tiller/templates/nova.conf.erb /etc/tiller/templates/nova.conf.erb
ADD data/tiller/templates/admin-openrc.erb /etc/tiller/templates/admin-openrc.erb
ADD data/tiller/templates/demo-openrc.erb /etc/tiller/templates/demo-openrc.erb

# Install Nova Controller Packages
RUN yum -y install openstack-nova-api openstack-nova-cert openstack-nova-conductor \
  openstack-nova-console openstack-nova-novncproxy openstack-nova-scheduler \
  python-novaclient

# Run Tiller to populate conf and RC files.
RUN /usr/local/bin/tiller

# Enable nova-controller services
RUN systemctl enable openstack-nova-api
RUN systemctl enable openstack-nova-cert
RUN systemctl enable openstack-nova-consoleauth
RUN systemctl enable openstack-nova-conductor
RUN systemctl enable openstack-nova-novncproxy
RUN systemctl enable openstack-nova-scheduler

# Initialize the Nova MySQL DB
RUN nova-manage db sync

# Expose Nova Controller TCP ports
EXPOSE 6080 6081 8773 8774 8775

# Start Init
CMD ["/usr/sbin/init"]
EOF
fi

echo 'Dockerfile generated. Now building image'

sudo docker build -t $IMAGE_NAME $HOME/docker-nova-controller

exit $?
