#!/bin/bash
#
# Script to run docker nova-controller container.
#
set -x
set -e

# Check for Root user
if [ "$(id -u)" != "0" ]; then
    echo "This script must be run as root or with sudo"
    exit 1
fi

# Configure the nova-controller image name
export IMAGE_NAME="${IMAGE_NAME:-nova-controller}"

# Configure the nova-controller container name
export CONTAINER_NAME="${CONTAINER_NAME:-nova-controller}"

# Configure the nova-controller Hostname
export NOVA_CONTROLLER_HOSTNAME="${NOVA_CONTROLLER_HOSTNAME:-$HOSTNAME}"

# Configure the nova-controller container DNS search order.
export DNS_SEARCH="${DNS_SEARCH:-example.com}"

docker run --privileged -d -h $NOVA_CONTROLLER_HOSTNAME --dns-search $DNS_SEARCH -v /sys/fs/cgroup:/sys/fs/cgroup:ro -p 8773:8773 -p 8774:8774 -p 8775:8775 -p 6080:6080 -p 6081:6081 -p 5672:5672 --name="$CONTAINER_NAME" $IMAGE_NAME

# Get the PID of the nova-controller container
CONTAINER_PID="$(docker inspect --format={{.State.Pid}} $CONTAINER_NAME)"

#Use nsenter to enter the namespaces of the running nova-controller container.
nsenter -m -u -n -i -p -t $CONTAINER_PID /bin/bash

exit $?
